# Mission 1

For each cell, execute the code and answer the question before moving on to the next.

In [ ]:
people = {"Gontran": 23,
          "Jason": 42,
          "Ayoub": 27}


for i in people:
  print(i)

Gontran
Jason
Ayoub

1. What does `i` correspond to?
To answer, you must use the terms "keys" and "values".

Answer: The variable i represents the keys of the dictionary, and we can access the corresponding values using people[i]. In this case, we will take on the values "Gontran," "Jason," and "Ayoub," which are the keys in the people dictionary.

In [ ]:
for i in people.keys():
  print(i)

Gontran
Jason
Ayoub

In [ ]:
for i in people.values():
  print(i)

23
42
27

2. What does `i` correspond to in the second last cell?  
What does `i` in the last cell correspond to?  
Why do you ask?

Answer: i corresponds to the keys (names) of the people dictionary because we are using people.keys() to iterate through the keys explicitly. So, i takes on the values "Gontran," "Jason," and "Ayoub."

i corresponds to the values (ages) of the people dictionary because you are using people.values() to iterate through the values explicitly. So, i takes on the values 23, 42, and 27.

It can help clarify the purpose or reason behind the code in question because there are often different ways to approach a problem in programming, and the choice between iterating over keys or values depends on the desired outcome.

In [ ]:
for i in people.items():
  print(i)
  print(type(i))

('Gontran', 23)
<class 'tuple'>
('Jason', 42)
<class 'tuple'>
('Ayoub', 27)
<class 'tuple'>

3. What is the type of object returned here called?

Answer: The type of object returned by people.items() is called a "tuple." In this specific case, each tuple contains two elements: the key (name) and the corresponding value (age)

In [ ]:
for i, age in people.items():
  print(age)

23
42
27

4. Here I can recover the age of the people. How could I retrieve their names?

Answer: By replacing "i" with name & replacing print(age) by print(name) you should retreive names in this items.

# Mission 2

In [ ]:
people = {"Gontran": 23,
          "Jason": 42,
          "Ayoub": "27",
          "Léo": [10,20,30],
          "Rosario": {"Juan": 3,
                      "Camelia": 6}}


for i in people.values():
  print(type(i))

<class 'int'>
<class 'int'>
<class 'str'>
<class 'list'>
<class 'dict'>

1. Does the above code allow me to confirm that I can have values of different types within a dictionary?

Answer: Yes, the code provided demonstrates that we can have values of different types within a dictionar. In people dictionary, we have values of various types, including integers (int), strings (str), lists (list), and dictionaries (dict). dictionaries are versatile data structures that can store values of different types as their values.

2. Can I have keys of different types within a dictionary? In this case all keys are the same type (str) but searching on internet, I saw that keys could be on differents types but they must be of immutable types.

Answer:

In [ ]:
people["Ayoub"] = int(people["Ayoub"])

for i in people.values():
  print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'list'>
<class 'dict'>

3. What did the above code allow me to do? the code allowed us to convert the value from a string to an integer in the people dictionary for the key "Ayoub." using the int() function.

Answer:

# Mission 3

In [ ]:
groups = {"groupe_1": ["Lam", "Ghizlaine", "Khaled", "Florian"],
          "groupe_2": ["Lucile", "Mbaye", "Cécile", "Rohan"],
          "groupe_3": ["Agathe", "Charlotte", "Charles", "Maxime"],
          "groupe_4": ["Gaelle", "Linh", "Meral"]}


for i in groups.values():
  print(i)

['Lam', 'Ghizlaine', 'Khaled', 'Florian']
['Lucile', 'Mbaye', 'Cécile', 'Rohan']
['Agathe', 'Charlotte', 'Charles', 'Maxime']
['Gaelle', 'Linh', 'Meral']

1. What is the type of each value?  
How do I get into each list?

Answer: The type of each value is 'list'.

So, to access each individual list of names, we would use the respective keys in the groups dictionary. For example, groups["groupe_1"] would give you the list ['Lam', 'Ghizlaine', 'Khaled', 'Florian'].

In [ ]:
for i in groups.values():
  for v in i:
    print(v)

Lam
Ghizlaine
Khaled
Florian
Lucile
Mbaye
Cécile
Rohan
Agathe
Charlotte
Charles
Maxime
Gaelle
Linh
Meral

2. How did I get into each list?  
Take the time to explain your reasoning for answering this question.

Answer:Le code utilise une structure de boucle for imbriquée pour accéder à chaque élément de chaque liste dans le dictionnaire groups et les imprimer un par un.

La première boucle for : for i in groups.values(): Cette boucle itère à travers les valeurs du dictionnaire groups.  i est la variable qui prend la valeur de chaque liste à chaque itération de la boucle

La deuxième boucle for imbriquée : for v in i:cette boucle itère à travers chaque élément de la liste actuellement stockée dans la variable i. Par exemple, si i contient ["Lam", "Ghizlaine", "Khaled", "Florian"], alors v prendra successivement les valeurs de chaque nom dans cette liste.
À chaque itération de la boucle intérieure, quand on utilise print(v) pour imprimer la valeur de v, qui est un nom dans la liste. Cela affiche chaque nom dans chaque liste, un par un.