There is another type object we didn't talked about: `set`  
It looks like a `dictionaries`, but it's not a dictionaries.

In [ ]:
my_set = {"apple", "kiwi", "pineapple"}

In [ ]:
type(my_set)

set

Question : Why `myset` is not a object from `dict` class ?

Answer :dans cet exemple, c'est un set car il n'y a que des éléments non associés à une clé. la principale différence réside dans le fait qu'un dictionnaire est une collection de paires clé-valeur où on accéde aux valeurs par leurs clés, tandis qu'un set est une collection d'éléments uniques où on accéde aux éléments directement. Les dictionnaires sont utilisés lorsqu'on a besoin d'associer des valeurs à des clés, tandis que les set sont utilisés lorsqu'on a besoin de stocker des éléments uniques sans duplication.

Another specificity from `set` object is that they cannot have two items with the same values. Execute the cells below.

In [3]:
a_set = {"banana", "lemon", "lemon", "cherry", "lemon", "strawberry", "lemon" }

In [4]:
a_set

{'banana', 'cherry', 'lemon', 'strawberry'}

Question :  
Hom many items have the sets below ?
To answer, to can use your knowledge or the `len()` function.

In [7]:
this_set = {1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9}

In [10]:
number_of_item = len(this_set)
print(number_of_item)

9

Question :  
Does a set can contains elements with differents types ?

In [11]:
# try to make a set with objects with different types here:
answer = {"hey", 2, True, 2.33}
type(answer)
#oui un set peut contenir des types différent

set

Question :  
Considering the list below, there is a simple way to know the amount of unique values from this list. How ?

In [13]:
# Try to count the amount of unique values from this list, in one line of code.

a_list = [1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9]

count = len({x for x in a_list})
print(count)

9

There are four collection data types in the Python programming language:

* `List` is a collection which is ordered and changeable. Allows duplicate members.
* `Tuple` is a collection which is ordered and unchangeable. Allows duplicate members.
* `Set` is a collection which is unordered, unchangeable, and unindexed. No duplicate members, but you can remove items and add new items.
* `Dictionary` is a collection which is ordered and changeable. No duplicate members.

Question :   
Find a way to access to the first value of `this_set`

In [20]:
this_set = {1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9}

this_list = list(this_set)

first_value = this_list[0]
print("la premiere valeur du set est:",first_value)

la premiere valeur du set est: 1

Question :  
Find a way to add a value that will be unique in `a_set`

In [25]:
a_set = {'banana', 'cherry','lemon','strawberry'}

a_set.add('durian')

print(a_set)
#the add() method to add the value 'durian' to the set a_set. Since sets only allow unique values, it will be added to the set if it doesn't already exist, ensuring that it remains unique within the set.

{'banana', 'lemon', 'cherry', 'strawberry', 'durian'}

Question :  
Now, you have to add the value from `this_set` to `a_set`:

In [29]:
this_set = {1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9}
a_set = {'banana', 'cherry','lemon','strawberry'}

for value in this_set:
  a_set.add(value)

print(a_set)

{1, 2, 3, 4, 'banana', 5, 'lemon', 'cherry', 'strawberry', 6, 7, 8, 9}

Question :    
If you display a `set` object, it's not display with the same order you define it. What can you say about the order the element are display ?

Answer : The order in which elements are displayed when we print a set object in Python is not guaranteed to be the same as the order in which you defined or added the elements. Sets are unordered collections, which means they do not maintain a specific order for their elements. This behavior is by design, and it allows sets to provide fast membership tests and eliminate duplicates efficiently. While the elements may sometimes appear in a particular order due to implementation details, you should not rely on this order, and it can change between different Python versions or implementations.

Question :    
Find a way to display the elements that exist in both sets.

In [34]:
a_set = {"banana", "grapes", "cherry", "pineapple", "kiwi", "strawberry"}
b_set = {"lemon", "kiwi", "grapes", "blueberry", "watermelon"}

# Utiliser intersection_update pour modifier 'a_set' afin qu'il contienne uniquement les éléments présents dans les deux ensembles
a_set.intersection_update(b_set)

# Les éléments communs sont maintenant dans 'a_set'
elements_communs = a_set

# Afficher les éléments communs
print(elements_communs)

{'kiwi', 'grapes'}

There is other methods for `set` objects, that you can find [here](https://www.w3schools.com/python/python_ref_set.asp).